version: "3.5"

services:
  rabbitmq:
    image: rabbitmq
    
    networks:
      - mqnet
    ports: 
    - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbitMQ
  rabbitc:
    build: .
    depends_on:
      - rabbitmq
    networks:
      - mqnet
    links:
      - rabbitmq:rabbitmq

networks:
  mqnet:
    driver: bridge

    
      
        

           